version: "3.7"

services: 
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo12:0.0.1
    container_name: odoo12
    ports:
      - 8069:8069
    tty: true
    environment:
      - HOST=postgres12
      - PORT=5432
      - USER=general
      - PASSWORD=123456
    volumes:
      - odoo-web-data:/opt/odoo12/data
      - ./config:/opt/odoo12/config
      - ./addons:/opt/odoo12/extra-addons
    restart: always
    networks:
      - common
volumes:
  odoo-web-data:

networks:
  common:
    driver: bridge
    external: true