version: "3.7"

services: 
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: jodoo:12.0
    container_name: odoo12
    hostname: localhost
    ports:
      - 8069:8069
    tty: true
    environment: # configuracion para base de datos
      - HOST=postgres12
      - PORT=5432
      - USER=general
      - PASSWORD=123456
    volumes:
      - ./config:/opt/odoo12/config
      - ./addons:/opt/odoo12/extra-addons
      - odoo-data:/var/lib/odoo
    restart: always
    networks:
      - common
networks:
  common:
    driver: bridge
    external: true
volumes:
  odoo-data: