version: "3.7"

services: 
  postgres10:
    image: postgres:10
    container_name: postgres10
    environment: 
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: 
      - 5433:5432
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./sqls:/var/local/sqls
    restart: always
    networks:
      - odoo_web
  odoo:
    build: . 
    image: yusuke1998/odoo:12
    container_name: odoo12
    depends_on:
      - postgres10
    tty: true
    environment:
      - HOST=postgres10
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/opt/odoo12/data
      - ./config:/opt/odoo12/config
      - ./addons:/opt/odoo12/extra-addons
    ports:
      - 8069:8069
    restart: always
    networks:
      - odoo_web
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5051:80
    depends_on:
      - postgres10
    restart: always
    networks:
      - odoo_web
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo_web: